"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import NavBar from "./components/NavBar";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:from-dark-700 dark:to-dark-700 bg-gradient-to-r from-green-500 to-blue-500  bg-fixed pb-11 dark:text-white">
        <ThemeProvider attribute="class">
          <div className="my-14 grid grid-cols-12 gap-6 px-5 sm:px-20 md:mb-16 md:px-32 lg:mb-0 lg:px-36 xl:px-48 ">
            <div className="dark:bg-dark-500 shadow-custom-light dark:shadow-custom-dark col-span-12 h-full rounded-2xl bg-white p-4 text-center text-base lg:col-span-3">
              <SideBar />
            </div>
            <div className="shadow-custom-light dark:shadow-custom-dark dark:bg-dark-500 col-span-12 flex flex-col overflow-hidden rounded-2xl bg-white lg:col-span-9">
              <NavBar />
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
